import Image from "next/image";
import Nav from "./components/nav";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "flex min-h-screen flex-col items-center justify-between p-4"
        }
      >
        <main style={{ display: "block" }}>
          <Link href="\">
            <Image
              src="/images/logo-dan-vitoriano.jpeg"
              alt="logo"
              width={50}
              height={50}
              style={{ margin: "0 auto" }}
            />
          </Link>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
